"""
Expand exercise_library.json:
1. Add `scene` field to existing exercises
2. Append new exercises for home/office/outdoor scenarios
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "exercise_library.json"

with open(SRC, encoding="utf-8") as f:
    library = json.load(f)

SCENE_MAP = {
    "gym_001": ["gym", "home"],
    "gym_002": ["gym"],
    "gym_003": ["gym"],
    "gym_004": ["gym"],
    "gym_005": ["gym", "home"],
    "gym_006": ["gym"],
    "gym_007": ["gym"],
    "gym_008": ["gym"],
    "gym_009": ["gym", "home", "office", "outdoor"],
    "gym_010": ["gym"],
    "gym_011": ["gym"],
    "gym_012": ["gym", "home", "office", "outdoor"],
    "gym_013": ["gym", "home", "office", "outdoor"],
    "gym_014": ["gym", "home"],
    "gym_015": ["gym"],
}

for ex in library["exercises"]:
    ex["scene"] = SCENE_MAP.get(ex["exercise_id"], ["gym"])

NEW_EXERCISES = [
    # ── Bodyweight ──────────────────────────────────────────────────────────
    {
        "exercise_id": "bw_001",
        "name": "俯卧撑",
        "name_en": "Push-up",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["low", "moderate"],
            "target_body_parts": ["chest", "shoulders", "triceps"],
            "exercise_style": ["strength", "activation"],
            "contraindicated_flags": ["wrist_pressure", "shoulder_impingement_risk"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [8, 15],
            "rest_sec": 60,
            "estimated_duration_min": 8,
        },
        "muscles": {
            "primary": ["pectoralis_major"],
            "secondary": ["anterior_deltoid", "triceps_brachii"],
        },
        "difficulty": "beginner",
        "instructions": "俯卧位，双手与肩同宽，身体呈一条直线，屈肘下降至胸部贴近地面，推起还原。",
        "cues": ["核心收紧不塌腰", "肘部夹角45度", "下降比推起慢"],
    },
    {
        "exercise_id": "bw_002",
        "name": "宽距俯卧撑",
        "name_en": "Wide Push-up",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["low", "moderate"],
            "target_body_parts": ["chest", "shoulders"],
            "exercise_style": ["strength", "hypertrophy"],
            "contraindicated_flags": ["wrist_pressure", "shoulder_impingement_risk"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [8, 12],
            "rest_sec": 60,
            "estimated_duration_min": 7,
        },
        "muscles": {
            "primary": ["pectoralis_major"],
            "secondary": ["anterior_deltoid"],
        },
        "difficulty": "beginner",
        "instructions": "双手距离宽于肩膀约1.5倍，其余与标准俯卧撑相同，更多刺激胸部外侧。",
        "cues": ["手腕与肩同向", "下放时感受胸部拉伸", "保持躯干稳定"],
    },
    {
        "exercise_id": "bw_003",
        "name": "徒手深蹲",
        "name_en": "Bodyweight Squat",
        "scene": ["gym", "home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["low", "moderate"],
            "target_body_parts": ["quads", "glutes", "core"],
            "exercise_style": ["strength", "activation"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [12, 20],
            "rest_sec": 45,
            "estimated_duration_min": 7,
        },
        "muscles": {
            "primary": ["quadriceps", "gluteus_maximus"],
            "secondary": ["hamstrings", "core"],
        },
        "difficulty": "beginner",
        "instructions": "双脚与肩同宽，脚尖微朝外，屈膝下蹲至大腿平行于地面，起身还原。",
        "cues": ["膝盖追随脚尖方向", "挺胸收腹", "脚跟踩地不抬起"],
    },
    {
        "exercise_id": "bw_004",
        "name": "弓步蹲",
        "name_en": "Lunge",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["low", "moderate"],
            "target_body_parts": ["quads", "glutes", "hamstrings"],
            "exercise_style": ["strength", "activation"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [10, 12],
            "rest_sec": 60,
            "estimated_duration_min": 8,
        },
        "muscles": {
            "primary": ["quadriceps", "gluteus_maximus"],
            "secondary": ["hamstrings", "calves"],
        },
        "difficulty": "beginner",
        "instructions": "站立，单腿向前迈步，双膝弯曲至90度，前膝不超过脚尖，后膝不触地，起身还原。",
        "cues": ["躯干保持直立", "步幅足够大减少膝盖压力", "核心收紧保持平衡"],
    },
    {
        "exercise_id": "bw_005",
        "name": "臀桥",
        "name_en": "Glute Bridge",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["glutes", "hamstrings", "core"],
            "exercise_style": ["activation", "strength"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [15, 20],
            "rest_sec": 30,
            "estimated_duration_min": 6,
        },
        "muscles": {
            "primary": ["gluteus_maximus", "hamstrings"],
            "secondary": ["core", "erector_spinae"],
        },
        "difficulty": "beginner",
        "instructions": "仰卧，膝盖弯曲，脚踩地，向上推髋至躯干与大腿成一条直线，顶部收紧臀部，缓慢下降。",
        "cues": ["不要过度伸展腰椎", "顶部停留1-2秒", "脚踝正下方用力踩地"],
    },
    {
        "exercise_id": "bw_006",
        "name": "死虫",
        "name_en": "Dead Bug",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["core"],
            "exercise_style": ["activation"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [3],
            "reps_range": [8, 10],
            "rest_sec": 30,
            "estimated_duration_min": 5,
        },
        "muscles": {
            "primary": ["transverse_abdominis", "rectus_abdominis"],
            "secondary": ["hip_flexors"],
        },
        "difficulty": "beginner",
        "instructions": "仰卧，双臂垂直伸向天花板，双腿抬起90度。对侧手脚同时向远端伸展，保持腰背贴地，还原交替。",
        "cues": ["全程腰背不离地", "呼气时慢慢伸展", "动作速度要慢"],
    },
    {
        "exercise_id": "bw_007",
        "name": "鸟狗式",
        "name_en": "Bird Dog",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["core", "back"],
            "exercise_style": ["activation"],
            "contraindicated_flags": ["wrist_pressure"],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [3],
            "reps_range": [10, 12],
            "rest_sec": 30,
            "estimated_duration_min": 5,
        },
        "muscles": {
            "primary": ["transverse_abdominis", "erector_spinae"],
            "secondary": ["glutes", "deltoid"],
        },
        "difficulty": "beginner",
        "instructions": "四足支撑，对侧手和腿同时伸展至水平，保持脊柱中立，缓慢还原。",
        "cues": ["不要转动腰部", "眼睛看地面", "伸展时腰部不要下塌"],
    },
    {
        "exercise_id": "bw_008",
        "name": "超人式",
        "name_en": "Superman",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["back", "glutes"],
            "exercise_style": ["activation", "strength"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [12, 15],
            "rest_sec": 30,
            "estimated_duration_min": 5,
        },
        "muscles": {
            "primary": ["erector_spinae", "gluteus_maximus"],
            "secondary": ["hamstrings", "rear_deltoid"],
        },
        "difficulty": "beginner",
        "instructions": "俯卧，双臂向前伸展，同时将手臂、胸部和腿部抬离地面，保持2-3秒后下降。",
        "cues": ["颈部保持中立不过度仰头", "感受背部整体收缩", "呼气时发力"],
    },
    {
        "exercise_id": "bw_009",
        "name": "登山者",
        "name_en": "Mountain Climber",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["moderate", "high"],
            "target_body_parts": ["core", "shoulders", "full_body"],
            "exercise_style": ["cardio", "hiit", "activation"],
            "contraindicated_flags": ["wrist_pressure", "shoulder_impingement_risk"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "duration_range_sec": [20, 40],
            "rest_sec": 45,
            "estimated_duration_min": 7,
        },
        "muscles": {
            "primary": ["core", "hip_flexors"],
            "secondary": ["anterior_deltoid", "quads"],
        },
        "difficulty": "beginner",
        "instructions": "俯卧撑起始位置，双手支撑，交替快速将膝盖拉向胸部，保持髋部稳定。",
        "cues": ["不要顶臀", "核心全程收紧", "速度可以先慢后快"],
    },
    {
        "exercise_id": "bw_010",
        "name": "猫牛式",
        "name_en": "Cat-Cow",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["back", "core"],
            "exercise_style": ["mobility", "stretching"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [30, 60],
            "rest_sec": 15,
            "estimated_duration_min": 4,
        },
        "muscles": {
            "primary": ["erector_spinae", "multifidus"],
            "secondary": ["abdominals"],
        },
        "difficulty": "beginner",
        "instructions": "四足支撑，先拱背（猫式：低头、腹部向上），再塌腰（牛式：抬头、腹部向下），配合呼吸交替。",
        "cues": ["动作配合呼吸节律", "幅度适中不要过度", "适合久坐后放松"],
    },
    {
        "exercise_id": "bw_011",
        "name": "婴儿式",
        "name_en": "Child's Pose",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["back", "shoulders"],
            "exercise_style": ["stretching", "mobility"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [30, 60],
            "rest_sec": 15,
            "estimated_duration_min": 4,
        },
        "muscles": {
            "primary": ["latissimus_dorsi", "erector_spinae"],
            "secondary": ["gluteus_maximus"],
        },
        "difficulty": "beginner",
        "instructions": "跪坐，臀部坐向脚跟，双臂向前伸展，额头贴地或悬空，感受背部和肩膀拉伸。",
        "cues": ["深呼吸放松背部", "手臂尽量向前伸", "适合训练结束放松"],
    },
    {
        "exercise_id": "bw_012",
        "name": "眼镜蛇式",
        "name_en": "Cobra Stretch",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["back", "core"],
            "exercise_style": ["stretching", "mobility"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [20, 40],
            "rest_sec": 15,
            "estimated_duration_min": 4,
        },
        "muscles": {
            "primary": ["erector_spinae"],
            "secondary": ["abdominals", "anterior_deltoid"],
        },
        "difficulty": "beginner",
        "instructions": "俯卧，双手置于胸旁，用手臂力量缓慢撑起上半身，骨盆保持贴地，感受脊柱伸展。",
        "cues": ["肩膀远离耳朵", "不要锁死肘部", "适合久坐后放松腰背"],
    },
    {
        "exercise_id": "bw_013",
        "name": "站立腘绳肌拉伸",
        "name_en": "Standing Hamstring Stretch",
        "scene": ["gym", "home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["hamstrings", "back"],
            "exercise_style": ["stretching"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [30, 45],
            "rest_sec": 20,
            "estimated_duration_min": 4,
        },
        "muscles": {
            "primary": ["hamstrings"],
            "secondary": ["erector_spinae", "calves"],
        },
        "difficulty": "beginner",
        "instructions": "站立，单腿向前伸直脚尖朝上，身体向前弯曲感受大腿后侧拉伸，保持后换腿。",
        "cues": ["不要弹振", "背部保持平直", "适合跑步或下肢训练后"],
    },
    {
        "exercise_id": "bw_014",
        "name": "单腿臀桥",
        "name_en": "Single-Leg Glute Bridge",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["low", "moderate"],
            "target_body_parts": ["glutes", "hamstrings", "core"],
            "exercise_style": ["strength", "activation"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [10, 15],
            "rest_sec": 45,
            "estimated_duration_min": 8,
        },
        "muscles": {
            "primary": ["gluteus_maximus", "hamstrings"],
            "secondary": ["core", "hip_stabilizers"],
        },
        "difficulty": "beginner",
        "instructions": "仰卧，单腿屈膝脚踩地，另一腿伸直抬起，用支撑腿推髋至躯干成直线，缓慢下降。",
        "cues": ["骨盆保持水平不倾斜", "顶部停留1秒", "换腿完成相同组数"],
    },
    {
        "exercise_id": "bw_015",
        "name": "卷腹",
        "name_en": "Crunch",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["low"],
            "target_body_parts": ["core"],
            "exercise_style": ["strength", "endurance"],
            "contraindicated_flags": ["neck_strain", "spinal_flexion"],
        },
        "execution": {
            "equipment": ["mat", "bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [15, 20],
            "rest_sec": 30,
            "estimated_duration_min": 6,
        },
        "muscles": {
            "primary": ["rectus_abdominis"],
            "secondary": ["obliques"],
        },
        "difficulty": "beginner",
        "instructions": "仰卧，膝盖弯曲，双手轻放耳侧，卷起上背部至肩胛骨离地，缓慢下降，不要坐起来。",
        "cues": ["颈部不要用力拉扯", "腰背始终贴地", "感受腹部收缩"],
    },

    # ── Home with equipment ──────────────────────────────────────────────────
    {
        "exercise_id": "hm_001",
        "name": "哑铃俯身划船",
        "name_en": "Dumbbell Row",
        "scene": ["gym", "home"],
        "matching_tags": {
            "intensity": ["low", "moderate"],
            "target_body_parts": ["back", "biceps"],
            "exercise_style": ["strength", "hypertrophy"],
            "contraindicated_flags": ["lower_back_load"],
        },
        "execution": {
            "equipment": ["dumbbell"],
            "sets_range": [3, 4],
            "reps_range": [10, 12],
            "rest_sec": 60,
            "estimated_duration_min": 9,
        },
        "muscles": {
            "primary": ["latissimus_dorsi", "rhomboids"],
            "secondary": ["biceps_brachii", "rear_deltoid"],
        },
        "difficulty": "beginner",
        "instructions": "单手扶桌或椅子，对侧手持哑铃，躯干平行于地面，将哑铃拉至腰侧，肘部贴近身体，缓慢下降。",
        "cues": ["肩胛骨主动内收", "不要转动躯干", "肘部向后向上带动"],
    },
    {
        "exercise_id": "hm_002",
        "name": "哑铃肩推",
        "name_en": "Dumbbell Shoulder Press",
        "scene": ["gym", "home"],
        "matching_tags": {
            "intensity": ["moderate", "high"],
            "target_body_parts": ["shoulders", "triceps"],
            "exercise_style": ["strength", "hypertrophy"],
            "contraindicated_flags": ["shoulder_impingement_risk"],
        },
        "execution": {
            "equipment": ["dumbbell"],
            "sets_range": [3, 4],
            "reps_range": [8, 12],
            "rest_sec": 75,
            "estimated_duration_min": 10,
        },
        "muscles": {
            "primary": ["deltoid"],
            "secondary": ["triceps_brachii", "upper_trapezius"],
        },
        "difficulty": "beginner",
        "instructions": "坐立或站立，哑铃置于肩部两侧，垂直推起至手臂伸直，缓慢下降。",
        "cues": ["不要耸肩", "核心收紧稳定躯干", "手腕保持中立"],
    },
    {
        "exercise_id": "hm_003",
        "name": "哑铃罗马尼亚硬拉",
        "name_en": "Dumbbell RDL",
        "scene": ["gym", "home"],
        "matching_tags": {
            "intensity": ["moderate"],
            "target_body_parts": ["hamstrings", "glutes", "back"],
            "exercise_style": ["strength", "hypertrophy"],
            "contraindicated_flags": ["lower_back_load"],
        },
        "execution": {
            "equipment": ["dumbbell"],
            "sets_range": [3, 4],
            "reps_range": [10, 12],
            "rest_sec": 75,
            "estimated_duration_min": 10,
        },
        "muscles": {
            "primary": ["hamstrings", "gluteus_maximus"],
            "secondary": ["erector_spinae"],
        },
        "difficulty": "beginner",
        "instructions": "站立持哑铃，保持膝盖微弯，以髋为轴向前俯身，哑铃沿腿前侧下滑，感受腘绳肌拉伸，用臀部发力站起。",
        "cues": ["背部全程保持平直", "髋部向后推", "不要低头"],
    },
    {
        "exercise_id": "hm_004",
        "name": "哑铃酒杯深蹲",
        "name_en": "Dumbbell Goblet Squat",
        "scene": ["gym", "home"],
        "matching_tags": {
            "intensity": ["moderate"],
            "target_body_parts": ["quads", "glutes", "core"],
            "exercise_style": ["strength", "hypertrophy"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["dumbbell"],
            "sets_range": [3, 4],
            "reps_range": [10, 15],
            "rest_sec": 75,
            "estimated_duration_min": 10,
        },
        "muscles": {
            "primary": ["quadriceps", "gluteus_maximus"],
            "secondary": ["hamstrings", "core"],
        },
        "difficulty": "beginner",
        "instructions": "双手抱住一个哑铃置于胸前，深蹲至大腿平行于地面，保持躯干直立，起身。",
        "cues": ["肘部向内夹可辅助姿势", "膝盖朝向脚尖", "挺胸抬头"],
    },
    {
        "exercise_id": "hm_005",
        "name": "弹力带拉弓",
        "name_en": "Resistance Band Pull-Apart",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["shoulders", "back"],
            "exercise_style": ["activation"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["resistance_band"],
            "sets_range": [3, 4],
            "reps_range": [15, 20],
            "rest_sec": 45,
            "estimated_duration_min": 6,
        },
        "muscles": {
            "primary": ["rear_deltoid", "rotator_cuff"],
            "secondary": ["rhomboids", "middle_trapezius"],
        },
        "difficulty": "beginner",
        "instructions": "双手握住弹力带两端，手臂平举与肩同高，向两侧拉开弹力带至胸前展开，缓慢还原。",
        "cues": ["肩胛骨主动夹紧", "手臂保持伸直", "适合肩部热身或上班族纠姿"],
    },
    {
        "exercise_id": "hm_006",
        "name": "弹力带侧步走",
        "name_en": "Resistance Band Lateral Walk",
        "scene": ["gym", "home", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["glutes", "quads"],
            "exercise_style": ["activation"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["resistance_band"],
            "sets_range": [3, 4],
            "reps_range": [15, 20],
            "rest_sec": 30,
            "estimated_duration_min": 6,
        },
        "muscles": {
            "primary": ["gluteus_medius", "gluteus_maximus"],
            "secondary": ["quadriceps", "hip_abductors"],
        },
        "difficulty": "beginner",
        "instructions": "弹力带套在膝盖上方或脚踝处，半蹲位，向侧面横向迈步，双腿交替，保持髋膝一致。",
        "cues": ["保持微蹲姿势全程", "步幅均匀", "适合下肢激活热身"],
    },
    {
        "exercise_id": "hm_007",
        "name": "哑铃反向弓步",
        "name_en": "Dumbbell Reverse Lunge",
        "scene": ["gym", "home"],
        "matching_tags": {
            "intensity": ["moderate"],
            "target_body_parts": ["quads", "glutes", "hamstrings"],
            "exercise_style": ["strength", "hypertrophy"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["dumbbell"],
            "sets_range": [3, 4],
            "reps_range": [10, 12],
            "rest_sec": 60,
            "estimated_duration_min": 9,
        },
        "muscles": {
            "primary": ["quadriceps", "gluteus_maximus"],
            "secondary": ["hamstrings", "calves"],
        },
        "difficulty": "beginner",
        "instructions": "双手各持哑铃，单腿向后退步，双膝弯曲90度，前膝不超过脚尖，起身还原，交替进行。",
        "cues": ["比前弓步蹲对膝关节压力更小", "躯干保持直立", "重心在前腿"],
    },

    # ── Office / light activity ──────────────────────────────────────────────
    {
        "exercise_id": "of_001",
        "name": "靠墙胸部拉伸",
        "name_en": "Wall Chest Stretch",
        "scene": ["gym", "home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["chest", "shoulders"],
            "exercise_style": ["stretching", "mobility"],
            "contraindicated_flags": ["shoulder_impingement_risk"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [20, 40],
            "rest_sec": 15,
            "estimated_duration_min": 4,
        },
        "muscles": {
            "primary": ["pectoralis_major", "anterior_deltoid"],
            "secondary": [],
        },
        "difficulty": "beginner",
        "instructions": "单手扶墙，手臂平伸，身体缓慢向前旋转感受胸部和肩前侧拉伸，保持后换侧。",
        "cues": ["不要弹振", "肩膀下沉远离耳朵", "久坐后有效纠正驼背"],
    },
    {
        "exercise_id": "of_002",
        "name": "坐姿脊柱扭转",
        "name_en": "Seated Spinal Twist",
        "scene": ["gym", "home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["back", "core"],
            "exercise_style": ["mobility", "stretching"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [20, 30],
            "rest_sec": 15,
            "estimated_duration_min": 3,
        },
        "muscles": {
            "primary": ["obliques", "erector_spinae"],
            "secondary": [],
        },
        "difficulty": "beginner",
        "instructions": "坐在椅子或地上，保持脊柱直立，慢慢向一侧扭转躯干至极限，停留后换侧。",
        "cues": ["保持坐直不含胸", "呼气时深入扭转", "久坐必备动作"],
    },
    {
        "exercise_id": "of_003",
        "name": "提踵",
        "name_en": "Standing Calf Raises",
        "scene": ["gym", "home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["calves"],
            "exercise_style": ["activation", "endurance"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [15, 25],
            "rest_sec": 30,
            "estimated_duration_min": 5,
        },
        "muscles": {
            "primary": ["gastrocnemius", "soleus"],
            "secondary": [],
        },
        "difficulty": "beginner",
        "instructions": "站立，扶墙或椅背保持平衡，脚跟缓慢抬起至最高点，停顿后缓慢下降。",
        "cues": ["顶部短暂停留感受小腿收缩", "下降要慢", "可以单腿进行增加难度"],
    },
    {
        "exercise_id": "of_004",
        "name": "桌边俯卧撑",
        "name_en": "Incline Push-up",
        "scene": ["home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["chest", "shoulders", "triceps"],
            "exercise_style": ["activation", "strength"],
            "contraindicated_flags": ["wrist_pressure"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [10, 20],
            "rest_sec": 45,
            "estimated_duration_min": 6,
        },
        "muscles": {
            "primary": ["pectoralis_major"],
            "secondary": ["anterior_deltoid", "triceps_brachii"],
        },
        "difficulty": "beginner",
        "instructions": "双手扶桌面（或墙），身体成斜线，做俯卧撑动作。支撑面越高越容易，可根据能力调整。",
        "cues": ["核心收紧不塌腰", "适合办公室随时活动", "比标准俯卧撑更适合初学者"],
    },
    {
        "exercise_id": "of_005",
        "name": "椅子深蹲",
        "name_en": "Chair Squat",
        "scene": ["home", "office"],
        "matching_tags": {
            "intensity": ["very_low", "low"],
            "target_body_parts": ["quads", "glutes"],
            "exercise_style": ["activation", "strength"],
            "contraindicated_flags": ["knee_stress"],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [3, 4],
            "reps_range": [10, 15],
            "rest_sec": 30,
            "estimated_duration_min": 5,
        },
        "muscles": {
            "primary": ["quadriceps", "gluteus_maximus"],
            "secondary": ["hamstrings"],
        },
        "difficulty": "beginner",
        "instructions": "背对椅子站立，缓慢下蹲至臀部刚好触碰椅面即站起，不要完全坐下借力。",
        "cues": ["控制下蹲速度", "起身时核心用力", "膝盖不要内扣"],
    },
    {
        "exercise_id": "of_006",
        "name": "站立前屈",
        "name_en": "Standing Forward Fold",
        "scene": ["gym", "home", "office", "outdoor"],
        "matching_tags": {
            "intensity": ["very_low"],
            "target_body_parts": ["hamstrings", "back"],
            "exercise_style": ["stretching", "mobility"],
            "contraindicated_flags": [],
        },
        "execution": {
            "equipment": ["bodyweight"],
            "sets_range": [2, 3],
            "duration_range_sec": [30, 45],
            "rest_sec": 15,
            "estimated_duration_min": 4,
        },
        "muscles": {
            "primary": ["hamstrings"],
            "secondary": ["erector_spinae", "calves"],
        },
        "difficulty": "beginner",
        "instructions": "站立，慢慢弯腰向下，双手尽量触地或握住小腿，感受大腿后侧和背部拉伸，放松颈部。",
        "cues": ["膝盖可以微弯", "不要弹振", "深呼吸让身体慢慢放松下沉"],
    },
]

library["exercises"].extend(NEW_EXERCISES)

library["metadata"]["version"] = "2.0"
library["metadata"]["total_exercises"] = len(library["exercises"])
library["metadata"]["last_updated"] = "2026-05-12"
library["metadata"]["scenes"] = ["gym", "home", "office", "outdoor"]
library["tag_taxonomy"]["scene"] = ["gym", "home", "office", "outdoor"]

with open(SRC, "w", encoding="utf-8") as f:
    json.dump(library, f, ensure_ascii=False, indent=2)

print(f"Done! Total: {len(library['exercises'])} exercises")
for scene in ["gym", "home", "office", "outdoor"]:
    count = sum(1 for ex in library["exercises"] if scene in ex.get("scene", []))
    print(f"  {scene}: {count} exercises")
